import type { CompanyCard, BankAccount, SpecificationItemsRequest } from "./types"

// Моковые данные для компаний
export const mockCompanies: CompanyCard[] = [
  {
    id: "comp-1",
    name: "ООО «Техно Импорт»",
    inn: "7701234567",
    address: "г. Москва, ул. Тверская, д. 1, офис 123",
    email: "info@technoimport.ru",
    phone: "+7 (495) 123-45-67",
  },
  {
    id: "comp-2",
    name: "ООО «Глобал Трейд»",
    inn: "7702345678",
    address: "г. Москва, ул. Ленинградская, д. 15, офис 42",
    email: "contact@globaltrade.ru",
    phone: "+7 (495) 234-56-78",
  },
  {
    id: "comp-3",
    name: "ООО «Восток-Запад»",
    inn: "7703456789",
    address: "г. Москва, пр. Мира, д. 76, офис 301",
    email: "info@vostokzapad.ru",
    phone: "+7 (495) 345-67-89",
  },
]

// Моковые данные для банковских счетов
export const mockBankAccounts: Record<string, BankAccount[]> = {
  "comp-1": [
    {
      id: "acc-1",
      companyId: "comp-1",
      name: "Основной счет",
      bankName: "АО «Сбербанк»",
      accountNumber: "40702810123450101230",
      swift: "SABRRUMM",
      country: "Россия",
      currency: "RUB",
      isDefault: true,
    },
    {
      id: "acc-2",
      companyId: "comp-1",
      name: "Дополнительный счет",
      bankName: "АО «Альфа-Банк»",
      accountNumber: "40702810123450101231",
      swift: "ALFARUMM",
      country: "Россия",
      currency: "RUB",
      isDefault: false,
    },
    {
      id: "acc-3",
      companyId: "comp-1",
      name: "Валютный счет",
      bankName: "АО «Тинькофф Банк»",
      accountNumber: "40702840123450101232",
      swift: "TICSRUMM",
      country: "Россия",
      currency: "USD",
      isDefault: false,
    },
  ],
  "comp-2": [
    {
      id: "acc-4",
      companyId: "comp-2",
      name: "Основной счет",
      bankName: "ПАО «ВТБ»",
      accountNumber: "40702810123450101233",
      swift: "VTBRRUMM",
      country: "Россия",
      currency: "RUB",
      isDefault: true,
    },
  ],
  "comp-3": [
    {
      id: "acc-5",
      companyId: "comp-3",
      name: "Основной счет",
      bankName: "АО «Сбербанк»",
      accountNumber: "40702810123450101234",
      swift: "SABRRUMM",
      country: "Россия",
      currency: "RUB",
      isDefault: true,
    },
    {
      id: "acc-6",
      companyId: "comp-3",
      name: "Дополнительный счет",
      bankName: "АО «Альфа-Банк»",
      accountNumber: "40702810123450101235",
      swift: "ALFARUMM",
      country: "Россия",
      currency: "RUB",
      isDefault: false,
    },
    {
      id: "acc-7",
      companyId: "comp-3",
      name: "Резервный счет",
      bankName: "ПАО «ВТБ»",
      accountNumber: "40702810123450101236",
      swift: "VTBRRUMM",
      country: "Россия",
      currency: "RUB",
      isDefault: false,
    },
  ],
}

// Моковые данные для спецификаций
export const mockSpecifications: SpecificationItemsRequest[] = [
  {
    id: "spec-1",
    title: "Поставка электронных компонентов",
    supplier: "Guangzhou Electronics Ltd.",
    status: "approved",
    totalAmount: 6600,
    currency: "USD",
    createdAt: "2025-03-10T10:30:00Z",
    items: [
      {
        id: "item-1",
        name: "Микроконтроллеры STM32F4",
        code: "STM32F407VGT6",
        quantity: 500,
        unit: "шт",
        pricePerUnit: 12.5,
        totalPrice: 6250,
      },
      {
        id: "item-2",
        name: "Резисторы SMD 0805",
        code: "R-0805-10K",
        quantity: 10000,
        unit: "шт",
        pricePerUnit: 0.02,
        totalPrice: 200,
      },
      {
        id: "item-3",
        name: "Конденсаторы керамические",
        code: "C-0805-100nF",
        quantity: 5000,
        unit: "шт",
        pricePerUnit: 0.03,
        totalPrice: 150,
      },
    ],
    additionalInfo: "Срочный заказ для производственной линии",
  },
  {
    id: "spec-2",
    title: "Закупка текстильных изделий",
    supplier: "Shanghai Textile Group",
    status: "pending",
    totalAmount: 12000,
    currency: "USD",
    createdAt: "2025-03-15T14:15:00Z",
    items: [
      {
        id: "item-4",
        name: "Ткань хлопок 100%",
        code: "CTN-100",
        quantity: 1000,
        unit: "м",
        pricePerUnit: 8,
        totalPrice: 8000,
      },
      {
        id: "item-5",
        name: "Нитки швейные",
        code: "THR-PLS",
        quantity: 2000,
        unit: "шт",
        pricePerUnit: 2,
        totalPrice: 4000,
      },
    ],
  },
]
